import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.goto('./#board')
  await page.getByRole('button', { name: 'Reset sample' }).click()
  await page.getByRole('dialog', { name: 'Review this change' }).getByRole('button', { name: 'Confirm change' }).click()
})

test('understands a task title, previews the human-readable change, confirms, and persists it', async ({ page }) => {
  await page.getByRole('textbox', { name: 'Ask about the sample work' }).fill('Mark Finalize onboarding checklist as done')
  await page.getByRole('button', { name: 'Send' }).click()
  const dialog = page.getByRole('dialog', { name: 'Review this change' })
  await expect(dialog).toContainText('Finalize onboarding checklist')
  await expect(dialog).toContainText('In progress')
  await expect(dialog).toContainText('Complete')
  await dialog.getByRole('button', { name: 'Confirm change' }).click()
  await expect(page.getByLabel('Status for Finalize onboarding checklist')).toHaveValue('Complete')
  await page.reload()
  await expect(page.getByLabel('Status for Finalize onboarding checklist')).toHaveValue('Complete')
  await page.evaluate(() => window.scrollTo(0, 0))
})

test('supports a grounded conversational follow-up and asks before changing', async ({ page }) => {
  const input = page.getByRole('textbox', { name: 'Ask about the sample work' })
  await input.fill('When is Validate admin invite flow due?')
  await page.getByRole('button', { name: 'Send' }).click()
  await expect(page.getByText(/due Sep 11/)).toBeVisible()
  await input.fill('Mark that done')
  await page.getByRole('button', { name: 'Send' }).click()
  await expect(page.getByRole('dialog')).toContainText('Validate admin invite flow')
  await page.getByRole('dialog').getByRole('button', { name: 'Cancel' }).click()
  await expect(page.getByLabel('Status for Validate admin invite flow')).toHaveValue('Planned')
})

test('makes direct status and owner controls explicit, reviewable, and undoable', async ({ page }) => {
  const status = page.getByLabel('Status for Instrument workspace-created event')
  await status.selectOption('In review')
  await expect(page.getByRole('dialog')).toContainText('Instrument workspace-created event')
  await page.getByRole('dialog').getByRole('button', { name: 'Confirm change' }).click()
  await expect(status).toHaveValue('In review')
  const owner = page.getByLabel('Owner for Instrument workspace-created event')
  await owner.selectOption('Maya Chen')
  await expect(page.getByRole('dialog')).toContainText('Jon Bell')
  await page.getByRole('dialog').getByRole('button', { name: 'Confirm change' }).click()
  await expect(owner).toHaveValue('Maya Chen')
  await page.getByRole('button', { name: 'Undo last change' }).click()
  await expect(page.getByRole('dialog')).toContainText('Maya Chen')
  await page.getByRole('dialog').getByRole('button', { name: 'Confirm change' }).click()
  await expect(owner).toHaveValue('Jon Bell')
})

test('handles bulk, unsupported, clear chat, and cancelled preview safely', async ({ page }) => {
  await page.getByRole('button', { name: 'Complete tasks in review' }).click()
  await expect(page.getByRole('dialog')).toContainText('Review trial nurture copy')
  await page.getByRole('dialog').getByRole('button', { name: 'Cancel' }).click()
  await expect(page.getByLabel('Status for Review trial nurture copy')).toHaveValue('In review')
  const input = page.getByRole('textbox', { name: 'Ask about the sample work' })
  await input.fill('Book a flight')
  await page.getByRole('button', { name: 'Send' }).click()
  await expect(page.getByText(/I can help you review this sample board/)).toBeVisible()
  await input.fill('Assign Review trial nurture copy to Jon Bell')
  await page.getByRole('button', { name: 'Send' }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Clear chat' }).click()
  await expect(page.getByText('Your conversation is clear.')).toBeVisible()
  await expect(page.getByRole('dialog')).toContainText('Review trial nurture copy')
  await page.keyboard.press('Escape')
})

test('keeps controls usable without horizontal overflow on a mobile viewport', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.reload()
  await expect(page.getByRole('heading', { name: 'A calmer way to move work forward.' })).toBeVisible()
  await expect(page.getByLabel('Status for Finalize onboarding checklist')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByLabel('Owner for Review trial nurture copy').focus()
  await page.keyboard.press('Tab')
})

test('renders the complete desktop workspace with its conversation controls', async ({ page }) => {
  await page.evaluate(() => window.scrollTo(0, 0))
  await expect(page.getByRole('heading', { name: 'A calmer way to move work forward.' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Talk it through' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Complete tasks in review' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})
